### ISSUE TITLE
Could anyone fix this error?

### ISSUE THREAD

**Issue by ohoneyd** [facebookresearch/CollaQ#19]
git submodule sync && git submodule update --init --recursive
cd third_party/sacred
git apply ../sacred.patch
cd ../smac
git apply ../smac.patch
cd ../pymarl
git apply ../pymarl.patch

error: patch failed: src/components/transforms.py:19
error: src/components/transforms.py: patch does not apply
error: patch failed: src/controllers/__init__.py:2
error: src/controllers/__init__.py: patch does not apply
error: patch failed: src/modules/agents/__init__.py:1
error: src/modules/agents/__init__.py: patch does not apply
error: patch failed: src/modules/critics/coma.py:67
error: src/modules/critics/coma.py: patch does not apply
error: patch failed: src/modules/mixers/vdn.py:7
error: src/modules/mixers/vdn.py: patch does not apply

**Comment by Marioooooooooooooo** [comment]
how do you fixed the problem, can you tell me?
