### ISSUE TITLE
env_info KeyError: 'obs_alone_shape'

### ISSUE THREAD

**Issue by DrZero0** [facebookresearch/CollaQ#7]
I built a virtual environment with python == 3.6.12 and installed the packages with requirements.txt. However, when I tried to run with the following command: 

python src/main.py --config=qmix --env-config=sc2 with env_args.map_name=MMM2

I got an error:
[ERROR 11:51:20] pymarl Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 41, in my_main
    run(_run, config, _log)
  File "/home/wang/files/MARL/CollaQ/src/run.py", line 54, in run
    run_sequential(args=args, logger=logger)
  File "/home/wang/files/MARL/CollaQ/src/run.py", line 101, in run_sequential
    "obs_alone": {"vshape": env_info["obs_alone_shape"], "group": "agents"},
KeyError: 'obs_alone_shape'

After that, I went to check the generation of 'env_info', and found that there was no such key 'obs_alone_shape': 
```python
def get_env_info(self):
        env_info = {"state_shape": self.get_state_size(),
                    "obs_shape": self.get_obs_size(),
                    "n_actions": self.get_total_actions(),
                    "n_agents": self.n_agents,
                    "episode_limit": self.episode_limit}
        return env_info
```
in file smac/env/multiagentenv.py

Was that because I had installed the packages in the wrong way? 
Hope to receive a reply soon.

**Comment by DrZero0** [comment]
It turns out that I applied the patches for smac and sacred after I installed the requirements so that the changes done in the patches didn't work. 
I made a silly mistake, sorry to bother.

**Comment by 4ever-Rain** [comment]
Got the same problem.
Should I install the packages with requirements.txt in a virtual environment?
Or apply the patches first, and then install the requirement.txt?
This is the first time I use patches. Could you give me some ideas for Installation? 
Thanks :)

**Comment by DrZero0** [comment]
> Got the same problem.
> Should I install the packages with requirements.txt in a virtual environment?
> Or apply the patches first, and then install the requirement.txt?
> This is the first time I use patches. Could you give me some ideas for Installation?
> Thanks :)

Sorry I can‘t remember exactly, but you may apply the patches before installing the requirements.txt. 
Hope I can help.

**Comment by 4ever-Rain** [comment]
Thanks for your help! It's a good idea to apply the patches before installing the requirements.txt.
My problem is caused by the python can not import the local smac files. It has worked now.

**Comment by gaoxiaomao** [comment]
> Thanks for your help! It's a good idea to apply the patches before installing the requirements.txt. My problem is caused by the python can not import the local smac files. It has worked now.
error: 打补丁失败：src/components/action_selectors.py:63
error: src/components/action_selectors.py：补丁未应用
error: 打补丁失败：src/components/transforms.py:19
error: src/components/transforms.py：补丁未应用
error: 打补丁失败：src/config/default.yaml:18
error: src/config/default.yaml：补丁未应用
error: 打补丁失败：src/config/envs/sc2.yaml:4
error: src/config/envs/sc2.yaml：补丁未应用
can you tell me how to fix the problme

> 
error: patch failed: src/components/transforms.py:19
error: src/components/transforms.py: patch does not apply
error: patch failed: src/controllers/init.py:2
error: src/controllers/init.py: patch does not apply
error: patch failed: src/modules/agents/init.py:1
error: src/modules/agents/init.py: patch does not apply
error: patch failed: src/modules/critics/coma.py:67
error: src/modules/critics/coma.py: patch does not apply
error: patch failed: src/modules/mixers/vdn.py:7
error: src/modules/mixers/vdn.py: patch does not apply

can you tell me how to fix the problem
