### ISSUE TITLE
Question of copyright of this repo

### ISSUE THREAD

**Issue by GoingMyWay** [facebookresearch/CollaQ#9]
Hi, I found files in this repo contain many 

```
# Copyright (c) Facebook, Inc. and its affiliates.
```

However, to my knowledge, this repo is mainly based on https://github.com/oxwhirl/pymarl. My question is: is it proper to add copyright claim in files from pymarl.

**Comment by yuandong-tian** [comment]
Thanks @GoingMyWay. We notice this issue and will update the repo soon (remove all files from pymarl and instead provide patches). We apologize for it. Note that it is required by our open source team to put the copyright header in all source codes to be released.

**Comment by GoingMyWay** [comment]
> Thanks @GoingMyWay. We notice this issue and will update the repo soon (remove all files from pymarl and instead provide patches). We apologize for it. Note that it is required by our open source team to put the copyright header in all source codes to be released.

Great, it is not a big problem.
